### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by WhiskyModz** [SsageParuders/ModGamesByInjectZygote#3]
growtopia crashes when opened

**Comment by SsageParuders** [comment]
This project was made for old version of growtopia. So you need to find new symbols of growtopia to hook.

I will update my projects when i have a free time, as i am busy recently.

Thank you for your support,dear bro.

**Comment by WhiskyModz** [comment]
Oh ok bro my bad
Thanks

**Comment by WhiskyModz** [comment]
.
